version: '3'

services:
  db:
    image: postgres
    expose:
      -  "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw1234
      - POSTGRES_DB=moviegeeks
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    depends_on:
      - db
      
  notebook:
    build: .
    command: jupyter notebook
    ports:
      - "8888:8888"
